title: CloudBees India Hackathon 2024
email: gbhat@cloudbees.com
description: >- # this means to ignore newlines until "baseurl:"
  CloudBees India Hackathon 2024; registration starting on 3rd July 2024.
  Exciting prices await.
  Build your awesome project and wow everyone

theme: minima
plugins:
  - jekyll-feed

domain: cb-india-hackathon.github.io
url: https://cb-india-hackathon.github.io
